# Notebook 02 - Business Understanding

## Objetivo

Este notebook tem como objetivo responder às principais perguntas de negócio que irão direcionar o desenvolvimento do dashboard.

As análises incluem:

- Distribuição de cargos
- Distribuição de senioridade
- Modalidade de trabalho
- Setores que mais contratam
- Empresas com mais vagas
- Localizações com mais oportunidades
- Skills mais demandadas
- Análise salarial
- Definição dos KPIs do dashboard

In [1]:
import pandas as pd
import numpy as np
import ast
import re

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [2]:
df = pd.read_csv("../data/data_science_job_posts_2025.csv")

df.head()

,job_title,seniority_level,status,company,location,post_date,headquarter,industry,ownership,company_size,revenue,salary,skills
0,data scientist,senior,hybrid,company_003,"Grapevine, TX . Hybrid",17 days ago,"Bentonville, AR, US",Retail,Public,€352.44B,Public,"€100,472 - €200,938","['spark', 'r', 'python', 'scala', 'machine lea..."
1,data scientist,lead,hybrid,company_005,"Fort Worth, TX . Hybrid",15 days ago,"Detroit, MI, US",Manufacturing,Public,"155,030",€51.10B,"€118,733","['spark', 'r', 'python', 'sql', 'machine learn..."
2,data scientist,senior,on-site,company_007,"Austin, TX . Toronto, Ontario, Canada . Kirkla...",a month ago,"Redwood City, CA, US",Technology,Public,"25,930",€33.80B,"€94,987 - €159,559","['aws', 'git', 'python', 'docker', 'sql', 'mac..."
3,data scientist,senior,hybrid,company_008,"Chicago, IL . Scottsdale, AZ . Austin, TX . Hy...",8 days ago,"San Jose, CA, US",Technology,Public,"34,690",€81.71B,"€112,797 - €194,402","['sql', 'r', 'python']"
4,data scientist,NaN,on-site,company_009,On-site,3 days ago,"Stamford, CT, US",Finance,Private,"1,800",Private,"€114,172 - €228,337",[]

In [3]:
print(f"Quantidade de registros: {df.shape[0]}")
print(f"Quantidade de colunas: {df.shape[1]}")

df.info()

Quantidade de registros: 944
Quantidade de colunas: 13
<class 'pandas.DataFrame'>
RangeIndex: 944 entries, 0 to 943
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   job_title        941 non-null    str
 1   seniority_level  884 non-null    str
 2   status           688 non-null    str
 3   company          944 non-null    str
 4   location         942 non-null    str
 5   post_date        944 non-null    str
 6   headquarter      944 non-null    str
 7   industry         944 non-null    str
 8   ownership        897 non-null    str
 9   company_size     944 non-null    str
 10  revenue          929 non-null    str
 11  salary           944 non-null    str
 12  skills           944 non-null    str
dtypes: str(13)
memory usage: 96.0 KB

In [4]:
df.columns.tolist()

['job_title',
 'seniority_level',
 'status',
 'company',
 'location',
 'post_date',
 'headquarter',
 'industry',
 'ownership',
 'company_size',
 'revenue',
 'salary',
 'skills']

In [5]:
df["job_title"].value_counts(dropna=False)

job_title
data scientist               856
machine learning engineer     80
data engineer                  4
NaN                            3
data analyst                   1
Name: count, dtype: int64

In [6]:
job_title_pct = (
    df["job_title"]
    .value_counts(normalize=True, dropna=False)
    .mul(100)
    .round(2)
)

job_title_pct

job_title
data scientist               90.68
machine learning engineer     8.47
data engineer                 0.42
NaN                           0.32
data analyst                  0.11
Name: proportion, dtype: float64

In [7]:
df["seniority_level"].value_counts(dropna=False)

seniority_level
senior      630
lead        116
midlevel    113
NaN          60
junior       25
Name: count, dtype: int64

In [8]:
seniority_pct = (
    df["seniority_level"]
    .value_counts(normalize=True, dropna=False)
    .mul(100)
    .round(2)
)

seniority_pct

seniority_level
senior      66.74
lead        12.29
midlevel    11.97
NaN          6.36
junior       2.65
Name: proportion, dtype: float64

In [9]:
df["status"].value_counts(dropna=False)

status
on-site    363
NaN        256
hybrid     207
remote     118
Name: count, dtype: int64

In [10]:
status_pct = (
    df["status"]
    .value_counts(normalize=True, dropna=False)
    .mul(100)
    .round(2)
)

status_pct

status
on-site    38.45
NaN        27.12
hybrid     21.93
remote     12.50
Name: proportion, dtype: float64

In [11]:
df["industry"].value_counts(dropna=False).head(15)

industry
Technology       582
Finance          127
Retail           110
Healthcare        83
Education         19
Energy            12
Manufacturing      7
Logistics          4
Name: count, dtype: int64

In [12]:
industry_pct = (
    df["industry"]
    .value_counts(normalize=True, dropna=False)
    .mul(100)
    .round(2)
    .head(15)
)

industry_pct

industry
Technology       61.65
Finance          13.45
Retail           11.65
Healthcare        8.79
Education         2.01
Energy            1.27
Manufacturing     0.74
Logistics         0.42
Name: proportion, dtype: float64

In [13]:
df["company"].value_counts(dropna=False).head(20)

company
company_134    30
company_003    24
company_395    21
company_941    21
company_244    20
company_917    20
company_273    19
company_844    18
company_008    17
company_421    13
company_983    13
company_291    11
company_316    11
company_233     9
company_081     8
company_171     8
company_083     8
company_980     8
company_270     7
company_288     7
Name: count, dtype: int64

In [14]:
df["location"].value_counts(dropna=False).head(20)

location
Bengaluru, Karnataka, India             52
Fully Remote                            35
New York, NY                            22
United States                           22
On-site                                 18
San Francisco, CA                       17
Mountain View, CA                       17
Sunnyvale, CA                           13
Bengaluru, Karnataka, India . Hybrid    12
Hybrid                                  12
San Diego, CA                           11
New York, NY . Hybrid                   11
Seattle, WA                             10
Hyderabad, Telangana, India             10
Atlanta, GA                              9
Singapore, Singapore                     9
McLean, VA                               9
Bellevue, WA                             8
London, England, United Kingdom          8
Toronto, Ontario, Canada                 7
Name: count, dtype: int64

In [15]:
df["skills"].head(10)

0    ['spark', 'r', 'python', 'scala', 'machine lea...
1    ['spark', 'r', 'python', 'sql', 'machine learn...
2    ['aws', 'git', 'python', 'docker', 'sql', 'mac...
3                               ['sql', 'r', 'python']
4                                                   []
5    ['scikit-learn', 'python', 'scala', 'sql', 'ma...
6                                                   []
7                                 ['machine learning']
8                                                   []
9                                                   []
Name: skills, dtype: str

In [16]:
def parse_skills(value):
    if pd.isna(value):
        return []

    if isinstance(value, list):
        return value

    try:
        parsed = ast.literal_eval(value)

        if isinstance(parsed, list):
            return [
                str(skill).strip().lower()
                for skill in parsed
            ]
    except:
        pass

    return [
        skill.strip().lower()
        for skill in str(value).split(",")
        if skill.strip()
    ]

In [17]:
df["skills_list"] = df["skills"].apply(parse_skills)

df[["skills", "skills_list"]].head()

,skills,skills_list
0,"['spark', 'r', 'python', 'scala', 'machine lea...","[spark, r, python, scala, machine learning, te..."
1,"['spark', 'r', 'python', 'sql', 'machine learn...","[spark, r, python, sql, machine learning]"
2,"['aws', 'git', 'python', 'docker', 'sql', 'mac...","[aws, git, python, docker, sql, machine learni..."
3,"['sql', 'r', 'python']","[sql, r, python]"
4,[],[]

In [18]:
df_skills = (
    df.explode("skills_list")
      .rename(columns={"skills_list": "skill"})
)

df_skills = df_skills[df_skills["skill"].notna()]
df_skills = df_skills[df_skills["skill"] != ""]

df_skills.head()

,job_title,seniority_level,status,company,location,post_date,headquarter,industry,ownership,company_size,revenue,salary,skills,skill
0,data scientist,senior,hybrid,company_003,"Grapevine, TX . Hybrid",17 days ago,"Bentonville, AR, US",Retail,Public,€352.44B,Public,"€100,472 - €200,938","['spark', 'r', 'python', 'scala', 'machine lea...",spark
0,data scientist,senior,hybrid,company_003,"Grapevine, TX . Hybrid",17 days ago,"Bentonville, AR, US",Retail,Public,€352.44B,Public,"€100,472 - €200,938","['spark', 'r', 'python', 'scala', 'machine lea...",r
0,data scientist,senior,hybrid,company_003,"Grapevine, TX . Hybrid",17 days ago,"Bentonville, AR, US",Retail,Public,€352.44B,Public,"€100,472 - €200,938","['spark', 'r', 'python', 'scala', 'machine lea...",python
0,data scientist,senior,hybrid,company_003,"Grapevine, TX . Hybrid",17 days ago,"Bentonville, AR, US",Retail,Public,€352.44B,Public,"€100,472 - €200,938","['spark', 'r', 'python', 'scala', 'machine lea...",scala
0,data scientist,senior,hybrid,company_003,"Grapevine, TX . Hybrid",17 days ago,"Bentonville, AR, US",Retail,Public,€352.44B,Public,"€100,472 - €200,938","['spark', 'r', 'python', 'scala', 'machine lea...",machine learning

In [19]:
top_skills = (
    df_skills["skill"]
    .value_counts()
    .head(20)
)

top_skills

skill
python              640
machine learning    580
sql                 442
r                   343
aws                 218
deep learning       178
tensorflow          165
spark               161
azure               155
pytorch             148
tableau             116
gcp                 106
scikit-learn         91
scala                85
database             83
pandas               76
java                 73
hadoop               67
git                  65
numpy                60
Name: count, dtype: int64

In [20]:
skill_frequency = (
    df_skills
    .groupby("skill")["job_title"]
    .count()
    .sort_values(ascending=False)
    .reset_index(name="frequencia")
)

skill_frequency["percentual_vagas"] = (
    skill_frequency["frequencia"] / len(df) * 100
).round(2)

skill_frequency.head(20)

               skill  frequencia  percentual_vagas
0             python         638             67.58
1   machine learning         580             61.44
2                sql         442             46.82
3                  r         342             36.23
4                aws         217             22.99
5      deep learning         178             18.86
6         tensorflow         165             17.48
7              spark         161             17.06
8              azure         154             16.31
9            pytorch         148             15.68
10           tableau         116             12.29
11               gcp         105             11.12
12      scikit-learn          91              9.64
13             scala          85              9.00
14          database          83              8.79
15            pandas          76              8.05
16              java          73              7.73
17            hadoop          67              7.10
18               git          64              6.78
19             numpy          60              6.36

In [21]:
skills_by_seniority = (
    df_skills
    .groupby(["seniority_level", "skill"])
    .size()
    .reset_index(name="frequencia")
    .sort_values(
        ["seniority_level", "frequencia"],
        ascending=[True, False]
    )
)

skills_by_seniority.head(30)

   seniority_level             skill  frequencia
9           junior  machine learning          21
14          junior            python          17
4           junior     deep learning           9
19          junior               sql           8
16          junior                 r           7
21          junior        tensorflow           7
15          junior           pytorch           6
2           junior             azure           5
1           junior               aws           4
6           junior               gcp           4
13          junior            pandas           4
17          junior      scikit-learn           4
20          junior           tableau           4
12          junior             numpy           3
18          junior             spark           3
3           junior          database           2
8           junior             linux           2
10          junior        matplotlib           2
11          junior    neural network           2
0           junior           airflow           1
5           junior            docker           1
7           junior        kubernetes           1
36            lead  machine learning          79
41            lead            python          74
47            lead               sql          54
43            lead                 r          46
24            lead               aws          31
27            lead     deep learning          28
46            lead             spark          25
49            lead        tensorflow          25

In [22]:
top5_skills_by_seniority = (
    skills_by_seniority
    .groupby("seniority_level")
    .head(5)
)

top5_skills_by_seniority

    seniority_level             skill  frequencia
9            junior  machine learning          21
14           junior            python          17
4            junior     deep learning           9
19           junior               sql           8
16           junior                 r           7
36             lead  machine learning          79
41             lead            python          74
47             lead               sql          54
43             lead                 r          46
24             lead               aws          31
71         midlevel            python          98
65         midlevel  machine learning          85
77         midlevel               sql          65
73         midlevel                 r          46
52         midlevel               aws          25
102          senior            python         451
95           senior  machine learning         395
110          senior               sql         315
104          senior                 r         244
82           senior               aws         158

In [23]:
skills_by_industry = (
    df_skills
    .groupby(["industry", "skill"])
    .size()
    .reset_index(name="frequencia")
    .sort_values(
        ["industry", "frequencia"],
        ascending=[True, False]
    )
)

skills_by_industry.head(30)

     industry             skill  frequencia
9   Education  machine learning          11
13  Education            python          10
15  Education                 r           7
18  Education               sql           5
2   Education          database           2
3   Education     deep learning           2
12  Education            pandas           2
16  Education      scikit-learn           2
0   Education               aws           1
1   Education             azure           1
4   Education               gcp           1
5   Education               git           1
6   Education              java           1
7   Education             keras           1
8   Education             linux           1
10  Education    neural network           1
11  Education             numpy           1
14  Education           pytorch           1
17  Education             scipy           1
19  Education           tableau           1
20  Education        tensorflow           1
31     Energy            python           8
37     Energy               sql           6
33     Energy                 r           5
29     Energy  machine learning           4
27     Energy               git           3
25     Energy     deep learning           2
39     Energy        tensorflow           2
21     Energy           airflow           1
22     Energy               aws           1

In [24]:
top_industries = (
    df["industry"]
    .value_counts()
    .head(5)
    .index
)

top5_skills_by_industry = (
    skills_by_industry[
        skills_by_industry["industry"].isin(top_industries)
    ]
    .groupby("industry")
    .head(5)
)

top5_skills_by_industry

       industry             skill  frequencia
9     Education  machine learning          11
13    Education            python          10
15    Education                 r           7
18    Education               sql           5
2     Education          database           2
60      Finance            python          91
54      Finance  machine learning          88
67      Finance               sql          65
62      Finance                 r          31
42      Finance               aws          28
90   Healthcare            python          65
85   Healthcare  machine learning          52
92   Healthcare                 r          39
97   Healthcare               sql          35
73   Healthcare             azure          22
137      Retail  machine learning          95
144      Retail            python          95
146      Retail                 r          74
151      Retail               sql          73
147      Retail             scala          55
176  Technology            python         364
169  Technology  machine learning         322
184  Technology               sql         252
178  Technology                 r         183
156  Technology               aws         129

In [25]:
df["salary"].head(20)

0     €100,472 - €200,938
1                €118,733
2      €94,987 - €159,559
3     €112,797 - €194,402
4     €114,172 - €228,337
5     €196,371 - €251,170
6       €51,330 - €70,144
7     €121,480 - €132,440
8                €207,331
9                €219,201
10                €96,815
11      €62,697 - €89,293
12     €99,464 - €165,954
13    €112,343 - €117,823
14    €127,867 - €150,700
15               €134,266
16                €52,746
17    €126,956 - €198,196
18    €185,412 - €228,338
19                €80,123
Name: salary, dtype: str

In [26]:
def extract_salary_values(value):

    if pd.isna(value):
        return pd.Series([np.nan, np.nan, np.nan])

    numbers = re.findall(
        r"\d[\d,]*",
        str(value)
    )

    numbers = [
        int(num.replace(",", ""))
        for num in numbers
    ]

    if len(numbers) == 0:
        return pd.Series([np.nan, np.nan, np.nan])

    if len(numbers) == 1:
        salary_min = numbers[0]
        salary_max = numbers[0]
    else:
        salary_min = min(numbers)
        salary_max = max(numbers)

    salary_avg = (
        salary_min + salary_max
    ) / 2

    return pd.Series([
        salary_min,
        salary_max,
        salary_avg
    ])

In [27]:
df[
    ["salary_min",
     "salary_max",
     "salary_avg"]
] = df["salary"].apply(
    extract_salary_values
)

df[
    [
        "salary",
        "salary_min",
        "salary_max",
        "salary_avg"
    ]
].head(20)

                 salary  salary_min  salary_max  salary_avg
0   €100,472 - €200,938    100472.0    200938.0    150705.0
1              €118,733    118733.0    118733.0    118733.0
2    €94,987 - €159,559     94987.0    159559.0    127273.0
3   €112,797 - €194,402    112797.0    194402.0    153599.5
4   €114,172 - €228,337    114172.0    228337.0    171254.5
5   €196,371 - €251,170    196371.0    251170.0    223770.5
6     €51,330 - €70,144     51330.0     70144.0     60737.0
7   €121,480 - €132,440    121480.0    132440.0    126960.0
8              €207,331    207331.0    207331.0    207331.0
9              €219,201    219201.0    219201.0    219201.0
10              €96,815     96815.0     96815.0     96815.0
11    €62,697 - €89,293     62697.0     89293.0     75995.0
12   €99,464 - €165,954     99464.0    165954.0    132709.0
13  €112,343 - €117,823    112343.0    117823.0    115083.0
14  €127,867 - €150,700    127867.0    150700.0    139283.5
15             €134,266    134266.0    134266.0    134266.0
16              €52,746     52746.0     52746.0     52746.0
17  €126,956 - €198,196    126956.0    198196.0    162576.0
18  €185,412 - €228,338    185412.0    228338.0    206875.0
19              €80,123     80123.0     80123.0     80123.0

In [28]:
df[
    [
        "salary_min",
        "salary_max",
        "salary_avg"
    ]
].describe()

         salary_min    salary_max    salary_avg
count  9.440000e+02  9.440000e+02  9.440000e+02
mean   1.145134e+05  1.490456e+05  1.317795e+05
std    1.262089e+05  1.341397e+05  1.288144e+05
min    4.055000e+03  7.678000e+03  7.055000e+03
25%    6.828550e+04  8.237000e+04  7.637175e+04
50%    1.104585e+05  1.514690e+05  1.347240e+05
75%    1.461402e+05  2.009362e+05  1.697330e+05
max    2.739979e+06  2.739979e+06  2.739979e+06

In [29]:
salary_by_seniority = (
    df.groupby("seniority_level")["salary_avg"]
    .mean()
    .round(2)
    .sort_values(ascending=False)
)

salary_by_seniority

seniority_level
lead        150339.10
senior      135549.15
midlevel    100323.60
junior       87939.74
Name: salary_avg, dtype: float64

In [30]:
salary_by_industry = (
    df.groupby("industry")["salary_avg"]
    .mean()
    .round(2)
    .sort_values(ascending=False)
    .head(15)
)

salary_by_industry

industry
Retail           153748.45
Energy           134385.67
Technology       131770.69
Finance          126188.89
Healthcare       123990.27
Manufacturing    104063.36
Education         96321.84
Logistics         77152.12
Name: salary_avg, dtype: float64

In [31]:
salary_by_status = (
    df.groupby("status")["salary_avg"]
    .mean()
    .round(2)
    .sort_values(ascending=False)
)

salary_by_status

status
on-site    148707.65
hybrid     142310.13
remote     130867.44
Name: salary_avg, dtype: float64

In [32]:
total_vagas = len(df)

total_empresas = (
    df["company"]
    .nunique()
)

total_skills = (
    df_skills["skill"]
    .nunique()
)

salario_medio = (
    df["salary_avg"]
    .mean()
)

percentual_senior = (
    df["seniority_level"]
    .eq("senior")
    .mean() * 100
)

percentual_remote = (
    df["status"]
    .eq("remote")
    .mean() * 100
)

print(f"Total de vagas: {total_vagas}")
print(f"Total de empresas: {total_empresas}")
print(f"Total de skills únicas: {total_skills}")
print(f"Salário médio: €{salario_medio:,.2f}")
print(f"% vagas Senior: {percentual_senior:.2f}%")
print(f"% vagas Remote: {percentual_remote:.2f}%")

Total de vagas: 944
Total de empresas: 420
Total de skills únicas: 33
Salário médio: €131,779.50
% vagas Senior: 66.74%
% vagas Remote: 12.50%

In [33]:
cargo_mais_comum = (
    df["job_title"]
    .value_counts()
    .idxmax()
)

cargo_mais_comum_pct = (
    df["job_title"]
    .value_counts(normalize=True)
    .max() * 100
)

senioridade_mais_comum = (
    df["seniority_level"]
    .value_counts()
    .idxmax()
)

senioridade_mais_comum_pct = (
    df["seniority_level"]
    .value_counts(normalize=True)
    .max() * 100
)

setor_mais_comum = (
    df["industry"]
    .value_counts()
    .idxmax()
)

setor_mais_comum_pct = (
    df["industry"]
    .value_counts(normalize=True)
    .max() * 100
)

skill_mais_comum = (
    skill_frequency.iloc[0]["skill"]
)

skill_mais_comum_pct = (
    skill_frequency.iloc[0]["percentual_vagas"]
)

print(
    f"Cargo predominante: {cargo_mais_comum} ({cargo_mais_comum_pct:.2f}% das vagas)"
)

print(
    f"Senioridade predominante: {senioridade_mais_comum} ({senioridade_mais_comum_pct:.2f}% das vagas)"
)

print(
    f"Setor predominante: {setor_mais_comum} ({setor_mais_comum_pct:.2f}% das vagas)"
)

print(
    f"Skill mais demandada: {skill_mais_comum} ({skill_mais_comum_pct:.2f}% das vagas)"
)

Cargo predominante: data scientist (90.97% das vagas)
Senioridade predominante: senior (71.27% das vagas)
Setor predominante: Technology (61.65% das vagas)
Skill mais demandada: python (67.58% das vagas)

In [34]:
print("""
Conclusões iniciais para o dashboard:

1. A base é fortemente concentrada em vagas de Data Scientist.
2. A maior parte das vagas exige senioridade alta.
3. As skills são o principal ativo analítico da base.
4. A coluna salarial precisa ser tratada para análise.
5. Os setores apresentam bons insights de contratação.
6. O dashboard deve focar em Ciência de Dados e tendências de mercado.
""")

Conclusões iniciais para o dashboard:

1. A base é fortemente concentrada em vagas de Data Scientist.
2. A maior parte das vagas exige senioridade alta.
3. As skills são o principal ativo analítico da base.
4. A coluna salarial precisa ser tratada para análise.
5. Os setores apresentam bons insights de contratação.
6. O dashboard deve focar em Ciência de Dados e tendências de mercado.